In [3]:
pip install openpyxl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.4/251.4 kB 2.0 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [4]:
t = (1,2,3)
np.array(t)

array([1, 2, 3])

In [5]:
np.array( [1.0, 2, 3.5, 0.2, True] )

array([1. , 2. , 3.5, 0.2, 1. ])

In [6]:
nums = np.array(range(1, 101))
nums

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
nums[nums % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [22]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


In [29]:
array_1 = np.array([ 1, 5, 9, 12, 15, 7, 12, 9 ])
m = 12
n = 6
final_array = array_1[(array_1 > m) & (array_1 < n)]
print(final_array)

[]
